import { constant } from '../utils/constant';
import Age11Image from '../assets/themeImages/Age1.1.png';
import Age12Image from '../assets/themeImages/Age1.2.png';

export const ageGroupOneTheme = {
  isChild: true,
  isChild1: true,
  pageBackgroundColor: '#E5F3FF',
  headerBackgroundColor: '#87BBEC',
  navBarIconColorSelected: '#FFAF00',
  navBarIconColorUnSelected: '#999999',
  pageBackgroundImage1: Age11Image,
  pageBackgroundImage2: Age12Image,
  profilePageHeaderColor: '#CB8F6E',
  profilePageTableHeaderColor: '#CC8D6A',
  profilePageColouredTableRowColor: 'rgba(255, 255, 255, 0.5)',
  profilePageTransparentTableRowColor: '#FFDECC',
  profilePageRowDataEvenColor: '#333333',
  profilePageRowDataOddColor: '#333333',
  nameTextColorAtDashboard: '#3E6E9B',
  nameSubTextColorAtDashboard: '#3E6E9B',
  textColorCalendarCard: '#CC8D6A',
  borderColorCalendarCard: '#CC8D6A',
  textColorCalendarSlider: '#CC8D6A',
  textColorCalendarSliderOnHover: '#fff',
  textColorCalendarTime: 'BLACK',
  taskNotComplete: 'Black',
  updateTaskModalBackgroundColor: '#E5F3FF',
  updateTaskModalHeaderColor: '#87BBEC',
  rewardTitleTextColor: '#CB8F6E',
  commonModalHeaderBackground: '#87BBEC',
  commonModalBackground: '#E5F3FF',
  commonModalButtonColor: '#CB8F6E',
  commonModalCancelButtonBorder: '2px solid #CB8F6E',
  commonModalCancelButtontext: '#CB8F6E',
  commonModalTextStyle: '#FFFFFF',
  commonModalImageContainer: '1px solid #87BBEC',
  requestContainerTitleColor: '#333333',
  sidebarHover: '#FFCFA8',
  NoProfileImage: '#E5F3FF',
  HeaderNameColor: '#fff',
  NoTaskText: '#d93a11',
};
