import { constant } from '../utils/constant';
import Age31Image from '../assets/themeImages/Age3.1.png';
import Age32Image from '../assets/themeImages/Age3.2.png';

export const ageGroupThreeTheme = {
  isChild: true,
  isChild3: true,
  pageBackgroundColor: '#2D2D2D',
  headerBackgroundColor: '#FFAF00',
  navBarIconColorSelected: '#FFAF00',
  navBarIconColorUnSelected: '#999999',
  pageBackgroundImage1: Age31Image,
  pageBackgroundImage2: Age32Image,
  profilePageHeaderColor: '#FFAF00',
  profilePageTableHeaderColor: '#FFEBED',
  profilePageColouredTableRowColor: 'rgba(254, 239, 206, 0.5)',
  profilePageTransparentTableRowColor: '#FEEFCE',
  profilePageRowDataEvenColor: '#333333',
  profilePageRowDataOddColor: '#FFFFFF',
  nameTextColorAtDashboard: '#FFE1B4',
  nameSubTextColorAtDashboard: '#FFE1B4',
  textColorCalendarCard: '#FFAF00',
  borderColorCalendarCard: '#FFAF00',
  textColorCalendarSlider: '#FFAF00',
  textColorCalendarSliderOnHover: '#fff',
  textColorCalendarTime: '#FFF',
  taskNotComplete: '#fff',
  updateTaskModalBackgroundColor: '#FFAF00',
  updateTaskModalHeaderColor: '#FFFCFC',
  rewardTitleTextColor: '#FFAF00',
  commonModalHeaderBackground: '#FFAF00',
  commonModalBackground: '#FFFCFC',
  commonModalButtonColor: '#CB8F6E',
  commonModalCancelButtonBorder: '2px solid #CB8F6E',
  commonModalCancelButtontext: '#CB8F6E',
  commonModalTextStyle: '#FFFFFF',
  commonModalImageContainer: '1px solid #FFAF00',
  requestContainerTitleColor: '#FFFFFF',
  sidebarHover: '#FFCFA8',
  NoProfileImage: '#FFEBED',
  HeaderNameColor: '#fff',
  NoTaskText: '#FF9838',
};
