import { constant } from '../utils/constant';
import Age21Image from '../assets/themeImages/Age2.1.png';
import Age22Image from '../assets/themeImages/Age2.2.png';

export const ageGroupTwoTheme = {
  isChild: true,
  isChild2: true,
  pageBackgroundColor: '#022B51',
  headerBackgroundColor: '#87BBEC',
  navBarIconColorSelected: '#FFAF00',
  navBarIconColorUnSelected: '#999999',
  pageBackgroundImage1: Age21Image,
  pageBackgroundImage2: Age22Image,
  profilePageHeaderColor: '#FFEBED',
  profilePageTableHeaderColor: '#FFEBED',
  profilePageColouredTableRowColor: 'rgba(255, 235, 237, 0.5)',
  profilePageTransparentTableRowColor: '#FFA6AF',
  profilePageRowDataEvenColor: '#333333',
  profilePageRowDataOddColor: '#FFFFFF',
  nameTextColorAtDashboard: '#BEFBDE',
  nameSubTextColorAtDashboard: '#BEFBDE',
  textColorCalendarCard: '#FF7180',
  borderColorCalendarCard: '#FF7180',
  textColorCalendarSlider: '#FF7180',
  textColorCalendarSliderOnHover: '#fff',
  textColorCalendarTime: '#FFF',
  taskNotComplete: '#fff',
  updateTaskModalBackgroundColor: '#FF7180',
  updateTaskModalHeaderColor: '#FFFCFC',
  rewardTitleTextColor: '#FFEBED',
  commonModalHeaderBackground: '#FF7180',
  commonModalBackground: '#FFFCFC',
  commonModalButtonColor: '#CB8F6E',
  commonModalCancelButtonBorder: '2px solid #CB8F6E',
  commonModalCancelButtontext: '#CB8F6E',
  commonModalTextStyle: '#FFFFFF',
  commonModalImageContainer: '1px solid #FF7180',
  requestContainerTitleColor: '#FFFFFF',
  sidebarHover: '#FFCFA8',
  NoProfileImage: '#FFEBED',
  HeaderNameColor: '#fff',
  NoTaskText: '#FF9838',
};
